### ISSUE TITLE
Fiber Error

### ISSUE THREAD

**Issue by aadamsx** [MeteorPackaging/pdftk#2]
I just installed this version (instead of aadams:pdftk), and I now get the following:

 throw new Error("Meteor code must always run within a Fiber. " +
W20150220-12:43:36.315(-6)? (STDERR)           ^
W20150220-12:43:36.315(-6)? (STDERR) Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
W20150220-12:43:36.315(-6)? (STDERR)     at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
W20150220-12:43:36.315(-6)? (STDERR)     at Object.Meteor.bindEnvironment (packages/meteor/dynamics_nodejs.js:85:1)
W20150220-12:43:36.315(-6)? (STDERR)     at Object.execute (packages/meteor/helpers.js:117:1)
W20150220-12:43:36.315(-6)? (STDERR)     at Object.fillForm (packages/pdftk:pdftk/pdftk-wrapper.js:46:1)
W20150220-12:43:36.315(-6)? (STDERR)     at app/both/3-router/routes.js:474:15
W20150220-12:43:36.315(-6)? (STDERR)     at Object.oncomplete (fs.js:107:15)
=> Exited with code: 8

I'm calling this code in a Iron Router server side method:

```
xfdfData = XmlBuilder.create(obj, { version: '1.0',  encoding: 'UTF-8' });
```

After this I made a few node calls:

```
  fs.mkdir(filebox, function (e) {
    if(!e || e.code === 'EEXIST') {
      fs.writeFile(xfdfFile, xfdfData.end({ pretty: true }), function (err) {
        if (err) throw err;

        PDFTK.fillForm(templateFile, xfdfFile, pdfFile, function (err, buffer) {
          if (err) throw err;

          fs.readFile(pdfFile, function (err, data) {
            if (err) throw err;

            res.write(data);
            res.end();
          });
        });
      });
    } else {
      console.log(e);
    }
  });
```

Note: the error line 474 is `PDFTK.fillForm(templateFile, xfdfFile, pdfFile, function (err, buffer) {`

The call to the PDFTK package is inside a `fs.writeFile` callback, and itself has a callback... is the fact that you wrapped the node execute call in a Meteor.wrapAsync call conflicting with my approach?

**Comment by aadamsx** [comment]
I just replace this package with my fork aadams:pdftk, it works fine.
